#!/usr/bin/env python3

TRIGGER_RADIUS_M = 30.0
ENTRY_SPEED_MIN_KPH = 65.0
ENTRY_SPEED_MAX_KPH = 75.0
COUNTDOWN_SECONDS = 5

CRUISE_SPEED_KPH = 70.0
HOLD_SPEED_KPH = 50.0
DECEL_ACCEL = 3.0  # m/s^2
HOLD_DURATION_S = 5.0

GPS_FRESHNESS_S = 2.0
GPS_MAX_ACCURACY_M = 30.0

STATE_IDLE = "idle"
STATE_POSITION_SET = "position_set"
STATE_ARMED = "armed"
STATE_COUNTDOWN = "countdown"
STATE_RUNNING = "running"
STATE_COMPLETE = "complete"

LOCKED_STATES = {STATE_ARMED, STATE_COUNTDOWN, STATE_RUNNING}
